/*
 * This Java source file was generated by the Gradle 'init' task.
 * (Multi-line comment)
 */
package data;

public class App {
    public static void main(String[] args) {
        // Comment (one-line)

        // Statements - end with a semicolon
        // Print a blank line
        // System.out.println();

        // Text - String - start/end with " (double quote) (always in pairs)
        // "" - empty string
        // Parameter, Argument - data that go into parentheses
        // \ - escape character
        // \" - print a quote
        // System.out.println("Hello, world! My \"name\" is Drew!");
        // System.out.println("I like to program!");

        // System.out.println("Hello");
        // String - double quotes ("")
        // System.out.println("2$H");

        // char - single quotes ('')
        // System.out.println('$');

        // int - Integer type
        // System.out.println(2);
        // System.out.println(0);
        // System.out.println(-2);

        // double - Real number
        // System.out.println(2.0);
        // System.out.println(2.5);
        // System.out.println(-0.1);

        // boolean - True/False 
        // System.out.println(true);
        // System.out.println(false);
    }
}
